version: "3"

services:
  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ev_charging
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    # networks:
    #   - app-backend-tier
# volumes:
#   postgres-data:
#     driver: local

# networks:
#   app-backend-tier:
#     driver: bridge
